import { useState } from "react";
import { ArrowLeft, CheckCircle2, LoaderCircle, ShieldCheck, Upload } from "lucide-react";

const UpiPaymentStep = ({ intent, title, description, details = [], onSubmit, onBack }) => {
  const [form, setForm] = useState({ transactionReference: "", paymentDate: new Date().toISOString().slice(0, 10) });
  const [proof, setProof] = useState(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });
  const submit = async (event) => { event.preventDefault(); if (!proof) return setMessage({ type: "error", text: "Choose the payment screenshot." }); setBusy(true); setMessage({ type: "", text: "" }); try { await onSubmit({ ...form, proof }); setMessage({ type: "success", text: "Payment proof submitted. Status: Pending Verification. Official documents are issued only after Admin approval." }); } catch (error) { setMessage({ type: "error", text: error.response?.data?.message || error.message || "Payment proof could not be submitted." }); } finally { setBusy(false); } };
  return <section className="mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl lg:grid lg:grid-cols-[0.9fr_1.1fr]">
    <div className="bg-[#0B2948] p-6 text-white sm:p-9">{onBack && <button type="button" onClick={onBack} className="mb-5 inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 px-4 text-sm font-semibold"><ArrowLeft size={17} />Back</button>}<p className="text-xs font-bold uppercase tracking-[0.2em] text-[#E6CB83]">Secure UPI payment</p><h1 className="mt-3 text-2xl font-bold sm:text-3xl">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-300">{description}</p><dl className="mt-6 space-y-3 rounded-2xl border border-white/10 bg-white/5 p-4 text-sm">{details.map(([label, value]) => <div key={label} className="flex justify-between gap-4"><dt className="text-slate-300">{label}</dt><dd className="text-right font-semibold">{value}</dd></div>)}<div className="border-t border-white/10 pt-3"><div className="flex items-end justify-between gap-4"><dt className="font-semibold">Total Payable</dt><dd className="text-2xl font-bold text-[#E6CB83]">₹{Number(intent.totalPayable).toLocaleString("en-IN")}</dd></div></div></dl><div className="mt-5 text-sm"><p className="font-semibold">{intent.payeeName}</p><p className="mt-1 break-all text-slate-300">UPI ID: {intent.upiId}</p><p className="mt-1 text-xs text-slate-400">Reference: {intent.reference}</p></div></div>
    <div className="p-5 sm:p-9"><div className="mx-auto max-w-sm text-center"><img src={intent.qrDataUrl} alt={`UPI QR for INR ${intent.totalPayable}`} className="mx-auto w-full max-w-[280px] rounded-2xl border bg-white p-3 shadow-sm" /><p className="mt-3 text-sm font-semibold text-[#102A43]">Scan and pay exactly ₹{Number(intent.totalPayable).toLocaleString("en-IN")}</p><p className="mt-1 text-xs text-slate-500">Do not edit the amount in your UPI app.</p></div><form onSubmit={submit} className="mt-7 space-y-4">{message.text && <div role="alert" className={`rounded-xl border p-4 text-sm ${message.type === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`}>{message.type === "success" && <CheckCircle2 className="mr-2 inline" size={18} />}{message.text}</div>}<label className="block text-sm font-semibold text-slate-700">UTR / Transaction Reference<input required minLength="3" className="form-input mt-1" value={form.transactionReference} onChange={(e) => setForm({ ...form, transactionReference: e.target.value })} /></label><label className="block text-sm font-semibold text-slate-700">Payment Date<input required type="date" max={new Date().toISOString().slice(0, 10)} className="form-input mt-1" value={form.paymentDate} onChange={(e) => setForm({ ...form, paymentDate: e.target.value })} /></label><label className="block text-sm font-semibold text-slate-700">Payment Screenshot<span className="mt-1 flex min-h-14 cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 px-4 text-sm font-normal text-slate-600"><Upload size={20} />{proof?.name || "Choose JPG, PNG or WebP (max 5 MB)"}<input type="file" accept=".jpg,.jpeg,.png,.webp" required className="sr-only" onChange={(e) => setProof(e.target.files?.[0] || null)} /></span></label><p className="flex gap-2 text-xs leading-5 text-slate-500"><ShieldCheck size={17} className="shrink-0 text-[#287080]" />Your screenshot is stored privately and can only be reviewed by authorised Admin users.</p><button disabled={busy || message.type === "success"} className="primary-button min-h-12 w-full justify-center">{busy ? <><LoaderCircle className="mr-2 animate-spin" size={18} />Submitting...</> : "Submit Payment Proof"}</button></form></div>
  </div></section>;
};
export default UpiPaymentStep;
