import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Download, Eye, RefreshCw, Send, XCircle } from "lucide-react";
import API from "../services/api";
import { downloadProtectedFile } from "../utils/protectedFile";
import { EmptyState, ErrorState, PageHeader, StatusBadge, ToolbarButton } from "../components/admin/AdminUI";
const requestBlob = (url) => API.get(url, { responseType: "blob" });

const ReceiptPreview = ({ item }) => (
  <div className="min-h-0 flex-1 overflow-auto rounded-xl border border-amber-300 bg-[#fffdf8] p-5 sm:p-8">
    <div className="rounded-xl bg-[#071f3e] p-5 text-white">
      <p className="font-serif text-2xl font-bold tracking-wider">SWABHIMAN</p>
      <p className="mt-1 text-xs font-bold tracking-wide text-amber-300">SHIKSHA SANSKRITI SAMAJOTTHAN NYAS</p>
    </div>
    <h3 className="my-7 text-center font-serif text-3xl font-bold tracking-wide text-[#071f3e]">DONATION RECEIPT</h3>
    <dl className="mx-auto grid max-w-2xl gap-3 text-sm">
      {[
        ["Receipt number", item.receiptNumber],
        ["Donor name", item.donor?.name || "Anonymous"],
        ["Donation amount", `${item.currency} ${Number(item.baseAmount).toFixed(2)}`],
        ["Payment date", item.paymentDate ? new Date(item.paymentDate).toLocaleDateString("en-IN") : "Not recorded"],
        ["Payment mode", item.paymentMethod || item.provider],
        ["UTR / reference", item.transactionReference || "Not provided"],
      ].map(([label, value], index) => <div key={label} className={`grid gap-1 rounded-lg p-4 sm:grid-cols-[170px_1fr] ${index % 2 ? "bg-amber-50" : "bg-white"}`}><dt className="font-semibold uppercase text-slate-500">{label}</dt><dd className="font-bold text-slate-800">{value}</dd></div>)}
    </dl>
    <p className="mx-auto mt-7 max-w-2xl text-center text-sm text-slate-700">We gratefully acknowledge the donation received for the charitable activities of the organisation.</p>
    <div className="mx-auto mt-7 max-w-2xl rounded-xl border border-amber-400 bg-amber-50 p-4 text-center">
      <p className="font-bold tracking-wide text-[#071f3e]">SYSTEM-GENERATED RECEIPT</p>
      <p className="mt-1 text-xs text-slate-600">This receipt is electronically generated and does not require a physical or digital signature.</p>
    </div>
  </div>
);

const AdminDonations = () => {
  const [items, setItems] = useState([]); const [filter, setFilter] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(""); const [preview, setPreview] = useState(null);
  const load = useCallback(async () => { try { setError(""); const response = await API.get(`/admin/donations${filter ? `?status=${filter}` : ""}`); setItems(response.data); } catch (e) { setError(e.response?.data?.message || "Donations could not be loaded."); } }, [filter]);
  useEffect(() => { load(); }, [load]);
  const action = async (id, type) => { if (type === "approve" && !window.confirm("Confirm that this payment has been verified and issue its official receipt?")) return; let reason = ""; if (type === "reject") { const input = window.prompt("Rejection reason (optional). Cancel to keep the donation pending."); if (input === null) return; reason = input; } setBusy(id); try { if (type === "reject") await API.post(`/admin/donations/${id}/reject`, { reason }); else await API.post(`/admin/donations/${id}/${type}`); await load(); } catch (e) { setError(e.response?.data?.message || "Action failed."); } finally { setBusy(""); } };
  const openPreview = async (url, label) => { try { const response = await requestBlob(url); setPreview({ label, url: URL.createObjectURL(response.data), type: response.headers["content-type"] || response.data.type }); } catch (e) { setError(e.response?.data?.message || e.message); } };
  return <main className="space-y-6"><PageHeader eyebrow="Donation operations" title="Donation Verification" description="Review payment proof, resolve pending submissions and manage issued receipts." actions={<ToolbarButton onClick={load}><RefreshCw size={17} />Refresh</ToolbarButton>} />
    <div className="flex flex-wrap gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-sm">{[["", "All"], ["pending", "Pending"], ["verified", "Approved"], ["rejected", "Rejected"]].map(([value, label]) => <button key={label} onClick={() => setFilter(value)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${filter === value ? "bg-[#102A43] text-white" : "text-slate-600 hover:bg-slate-100"}`}>{label}</button>)}</div>{error && <ErrorState message={error} onRetry={load} />}
    <div className="grid gap-4">{items.map((item) => <article key={item._id} className={`rounded-2xl border bg-white p-5 shadow-sm ${item.status === "pending" ? "border-amber-300 ring-1 ring-amber-100" : "border-slate-200"}`}><div className="flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2"><h2 className="font-bold text-[#102A43]">{item.donor?.name || "Anonymous"}</h2><StatusBadge status={item.status} /></div><p className="mt-1 text-sm text-slate-500">{item.donor?.email} {item.donor?.phone && `• ${item.donor.phone}`}</p><p className="mt-3 text-2xl font-bold tracking-tight text-[#102A43]">{item.currency} {Number(item.baseAmount).toLocaleString("en-IN")}</p></div><dl className="grid grid-cols-2 gap-x-8 gap-y-3 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="text-xs text-slate-500">Mode</dt><dd className="font-semibold">{item.paymentMethod || item.provider}</dd></div><div><dt className="text-xs text-slate-500">UTR / Reference</dt><dd className="font-semibold">{item.transactionReference || "Not provided"}</dd></div><div><dt className="text-xs text-slate-500">Submitted</dt><dd>{new Date(item.createdAt).toLocaleString()}</dd></div><div><dt className="text-xs text-slate-500">Receipt</dt><dd>{item.receiptNumber || "Not issued"}</dd></div></dl></div>
      {item.paymentDate && <p className="mt-3 text-sm text-slate-600"><strong>Payment date:</strong> {new Date(item.paymentDate).toLocaleDateString()}</p>}{item.donorNote && <p className="mt-4 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">{item.donorNote}</p>}{item.status === "rejected" && <p className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-800"><strong>Rejection reason:</strong> {item.rejectionReason || "No reason recorded"}</p>}<div className="mt-4 flex flex-wrap gap-2">{item.proofFile && <button onClick={() => openPreview(`/admin/donations/${item._id}/proof`, "Payment proof")} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Eye size={16} />View proof</button>}{item.status === "pending" && <><button disabled={busy === item._id} onClick={() => action(item._id, "approve")} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><CheckCircle2 size={16} />Approve & generate receipt</button><button disabled={busy === item._id} onClick={() => action(item._id, "reject")} className="inline-flex items-center gap-2 rounded-lg bg-red-600 px-3 py-2 text-sm font-semibold text-white"><XCircle size={16} />Reject</button></>}{item.receiptNumber && <><button onClick={() => setPreview({ label: "Donation receipt", type: "receipt", item })} className="inline-flex items-center gap-2 rounded-lg bg-[#0B2948] px-3 py-2 text-sm font-semibold text-white"><Eye size={16} />View receipt</button><button onClick={() => downloadProtectedFile(() => requestBlob(`/admin/donations/${item._id}/receipt`), `${item.receiptNumber}.pdf`).catch((e) => setError(e.response?.data?.message || e.message))} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Download size={16} />Download receipt</button><button onClick={() => action(item._id, "resend")} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Send size={16} />Resend receipt</button></>}</div>
    </article>)}{!items.length && <div className="rounded-2xl border border-slate-200 bg-white shadow-sm"><EmptyState title={filter === "pending" ? "No pending donations" : "No donations in this view"} description="New manual donation submissions will appear here after donors upload payment proof." /></div>}</div>{preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div role="dialog" aria-modal="true" className="flex h-[90vh] w-full max-w-5xl flex-col rounded-2xl bg-white p-4"><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-bold">{preview.label}</h2><button className="rounded-lg border px-4 py-2 font-semibold" onClick={() => { if (preview.url) URL.revokeObjectURL(preview.url); setPreview(null); }}>Close preview</button></div>{preview.type === "receipt" ? <ReceiptPreview item={preview.item} /> : preview.type?.startsWith("image/") ? <img src={preview.url} alt={preview.label} className="min-h-0 flex-1 object-contain" /> : <iframe title={preview.label} src={preview.url} className="min-h-0 flex-1 rounded-lg border" />}</div></div>}</main>;
};
export default AdminDonations;
