import { useEffect, useState } from "react";
import { Edit3, Plus, RefreshCw, Trash2 } from "lucide-react";
import { Link } from "react-router-dom";
import API from "../services/api";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, ToolbarButton } from "../components/admin/AdminUI";

const AdminPostsList = () => {
  const [posts, setPosts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const fetchPosts = async () => { try { setLoading(true); setError(""); const response = await API.get("/posts"); setPosts(response.data); } catch (requestError) { setError(requestError.response?.data?.message || "Posts could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { fetchPosts(); }, []);
  const deletePost = async (id) => { if (!window.confirm("Delete this post permanently? This cannot be undone.")) return; try { setBusy(id); await API.delete(`/posts/${id}`); await fetchPosts(); } catch (requestError) { setError(requestError.response?.data?.message || "Post could not be deleted."); } finally { setBusy(""); } };
  return <main className="space-y-6"><PageHeader eyebrow="Public communication" title="Published Posts" description="Review, edit and manage the updates visible on the public website." actions={<><ToolbarButton onClick={fetchPosts}><RefreshCw size={17} />Refresh</ToolbarButton><Link to="/admin/upload" className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#102A43] px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-[#287080]"><Plus size={17} />New post</Link></>} />{error && <ErrorState message={error} onRetry={fetchPosts} />}<SectionCard>{loading ? <LoadingState label="Loading posts…" /> : !posts.length ? <EmptyState title="No posts published" description="Publish the first update to keep visitors informed about the Nyas's work." /> : <div className="grid gap-5 p-5 sm:grid-cols-2 xl:grid-cols-3">{posts.map((post) => <article key={post._id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="aspect-[16/10] bg-slate-100">{post.images?.[0] ? <img src={post.images[0]} alt="Post" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-sm text-slate-400">No image</div>}</div><div className="p-4"><p className="line-clamp-3 min-h-[4.5rem] text-sm leading-6 text-slate-700">{post.caption || "No caption"}</p><div className="mt-4 flex gap-2"><Link to={`/admin/edit/${post._id}`} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Edit3 size={16} />Edit</Link><button disabled={busy === post._id} onClick={() => deletePost(post._id)} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50"><Trash2 size={16} />Delete</button></div></div></article>)}</div>}</SectionCard></main>;
};
export default AdminPostsList;
