import { useEffect, useState } from "react";
import { CalendarClock, CheckCircle2, ClipboardList, Clock3, FileBadge2, RefreshCw, XCircle } from "lucide-react";
import API from "../services/api";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatCard, StatusBadge, ToolbarButton } from "../components/admin/AdminUI";

const AdminExamDashboard = () => {
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const load = () => { setError(""); API.get("/exams/admin/dashboard").then(({ data: value }) => setData(value)).catch((err) => setError(err.response?.data?.message || "Examination dashboard could not be loaded.")); };
  useEffect(load, []);
  if (error) return <ErrorState message={error} onRetry={load} />;
  if (!data) return <LoadingState label="Loading examination operations…" />;
  const current = data.current;
  return <div className="space-y-6"><PageHeader eyebrow="Examination operations" title="Examination Dashboard" description="Live registration status, review workload and annual examination activity." actions={<ToolbarButton onClick={load}><RefreshCw size={16} />Refresh</ToolbarButton>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Total" value={data.counts.total} icon={ClipboardList} /><StatCard label="Pending review" value={data.counts.pending} icon={Clock3} tone="gold" /><StatCard label="Approved" value={data.counts.approved} icon={CheckCircle2} tone="teal" /><StatCard label="Rejected" value={data.counts.rejected} icon={XCircle} tone="light" /><StatCard label="Admit Cards" value={data.counts.admitCardsGenerated} icon={FileBadge2} tone="light" /></section><section className="grid gap-6 lg:grid-cols-[1.1fr_1.9fr]"><SectionCard title="Current examination" description="Dates are enforced by the server.">{current ? <dl className="grid gap-4 p-5 text-sm sm:grid-cols-2"><div className="sm:col-span-2"><dt className="text-xs uppercase tracking-wide text-slate-500">Examination</dt><dd className="mt-1 text-lg font-bold text-[#102A43]">{current.title}</dd></div><div><dt className="text-slate-500">Registration</dt><dd className="mt-1"><StatusBadge status={current.registrationState} /></dd></div><div><dt className="text-slate-500">Closing</dt><dd className="mt-1 font-semibold">{new Date(current.registrationEnd).toLocaleString("en-IN")}</dd></div><div><dt className="text-slate-500">Exam date</dt><dd className="mt-1 font-semibold">{new Date(current.examDate).toLocaleDateString("en-IN")}</dd></div><div><dt className="text-slate-500">Public link</dt><dd className="mt-1 break-all font-semibold text-[#287080]">/exam-registration/{current.slug}</dd></div></dl> : <EmptyState title="No examination cycle" description="Create the annual examination cycle in Exam Settings." />}</SectionCard><SectionCard title="Recent applications" description="Newest applications requiring operational attention.">{data.recent.length ? <div className="divide-y">{data.recent.map((item) => <article key={item._id} className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="font-bold text-[#102A43]">{item.studentName}</p><p className="mt-1 text-xs text-slate-500">{item.applicationNumber} • {new Date(item.createdAt).toLocaleString("en-IN")}</p></div><StatusBadge status={item.status} /></article>)}</div> : <EmptyState title="No registrations yet" description="Applications will appear here after public submission." />}</SectionCard></section></div>;
};
export default AdminExamDashboard;
