import { useEffect, useState } from "react";
import { CreditCard, RefreshCw, Send, ShieldCheck } from "lucide-react";
import API from "../services/api";
import { EmptyState, ErrorState, LoadingState, PageHeader, SectionCard, StatusBadge, ToolbarButton } from "../components/admin/AdminUI";

const AdminPayments = () => {
  const [data, setData] = useState({ config: null, payments: [], deliveries: [] }); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState("");
  const load = async () => { setError(""); setLoading(true); try { const [config, payments, deliveries] = await Promise.all([API.get("/admin/payment-config"), API.get("/admin/payments"), API.get("/admin/deliveries")]); setData({ config: config.data, payments: payments.data, deliveries: deliveries.data }); } catch (requestError) { setError(requestError.response?.data?.message || "Payment administration data could not be loaded."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const resend = async (requestId) => { if (!window.confirm("Regenerate the ID card and certificate with the latest design, then resend them to the registered recipient?")) return; try { setBusy(requestId); await API.post(`/admin/deliveries/${requestId}/resend`); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Regeneration and resend failed."); } finally { setBusy(""); } };
  return <main className="space-y-6">
    <PageHeader eyebrow="Payment operations" title="Payments & Delivery" description="Monitor provider readiness, transaction outcomes and membership document delivery." actions={<ToolbarButton onClick={load}><RefreshCw size={17} />Refresh</ToolbarButton>} />
    {error && <ErrorState message={error} onRetry={load} />}{loading ? <SectionCard><LoadingState /></SectionCard> : <>
      {data.config && <section className="grid gap-4 md:grid-cols-2">{Object.entries(data.config).map(([purpose, config]) => <article key={purpose} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#287080]/10 text-[#287080]"><CreditCard size={21} /></span><StatusBadge status={config.provider} /></div><h2 className="mt-4 text-lg font-bold capitalize text-[#102A43]">{purpose} payments</h2><dl className="mt-4 grid grid-cols-2 gap-4 text-sm"><div><dt className="text-xs text-slate-500">Tax setup</dt><dd className="mt-1 font-semibold">{config.tax.enabled ? `${config.tax.rate}% ${config.tax.label}` : "Disabled"}</dd></div><div><dt className="text-xs text-slate-500">Credentials</dt><dd className="mt-1 flex items-center gap-1 font-semibold"><ShieldCheck size={15} />{config.credentialsConfigured ? "Configured" : "Missing"}</dd></div></dl></article>)}</section>}
      <SectionCard title="Recent transactions" description="Newest payment attempts across membership and donations.">{!data.payments.length ? <EmptyState title="No transactions yet" description="Verified payment activity will appear here when transactions are recorded." /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Provider</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Payment</th><th className="px-5 py-3">Fulfillment</th></tr></thead><tbody>{data.payments.map((item) => <tr key={item._id} className="border-b border-slate-100 last:border-0"><td className="px-5 py-4">{new Date(item.createdAt).toLocaleString()}</td><td className="px-4 py-4 capitalize">{item.purpose}</td><td className="px-4 py-4">{item.provider}</td><td className="px-4 py-4 font-bold">{item.currency} {item.totalAmount}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-5 py-4"><StatusBadge status={item.fulfillmentStatus} /></td></tr>)}</tbody></table></div><div className="divide-y md:hidden">{data.payments.map((item) => <article key={item._id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-bold capitalize text-[#102A43]">{item.purpose}</p><p className="text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></div><p className="font-bold">{item.currency} {item.totalAmount}</p></div><div className="mt-4 flex flex-wrap gap-2"><StatusBadge status={item.status} /><StatusBadge status={item.fulfillmentStatus} /></div></article>)}</div></>}</SectionCard>
      <SectionCard title="Membership document delivery" description="Delivery status for generated ID cards and certificates. Regenerate & resend always applies the latest approved document design.">{!data.deliveries.length ? <EmptyState title="No delivery records yet" description="Delivery attempts will appear after approved memberships generate documents." /> : <div className="divide-y divide-slate-100">{data.deliveries.map((item) => <article key={item._id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold text-[#102A43]">{item.recipient}</p><p className="mt-1 text-xs text-slate-500">Attempts: {item.attempts}{item.lastError ? ` • ${item.lastError}` : ""}</p></div><div className="flex flex-wrap items-center gap-3"><StatusBadge status={item.status} /><ToolbarButton disabled={busy === item.membershipRequestId} onClick={() => resend(item.membershipRequestId)}><Send size={16} />Regenerate & resend</ToolbarButton></div></article>)}</div>}</SectionCard>
    </>}
  </main>;
};
export default AdminPayments;
