import { useEffect, useRef, useState } from "react";
import { CreditCard, HeartHandshake, LoaderCircle, QrCode, ShieldCheck } from "lucide-react";
import UpiPaymentStep from "../components/UpiPaymentStep";
import { createDonationPayment, createDonationUpiIntent, getPublicPaymentConfig, openPaymentCheckout, submitDonationUpiProof } from "../services/paymentService";

const Donate = () => {
  const [form, setForm] = useState({ name: "", email: "", phone: "", amount: "" });
  const [config, setConfig] = useState(null); const [intent, setIntent] = useState(null); const [mode, setMode] = useState("upi"); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const gatewayKey = useRef(crypto.randomUUID());
  useEffect(() => { getPublicPaymentConfig().then((r) => { setConfig(r.data); if (!r.data.upi.donationEnabled && r.data.donation.gatewayEnabled) setMode("gateway"); }).catch(() => setError("Payment availability could not be loaded.")); }, []);
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const proceed = async (event) => { event.preventDefault(); setLoading(true); setError(""); setNotice(""); try { if (mode === "upi") setIntent((await createDonationUpiIntent(form)).data); else { const payment = await createDonationPayment(form, gatewayKey.current); await openPaymentCheckout({ transaction: payment.data, payer: { name: form.name, email: form.email, contact: form.phone }, onSuccess: () => setNotice("Thank you. Your verified donation receipt is being prepared."), onDismiss: () => setError("Payment was cancelled. No donation was recorded as successful.") }); } } catch (requestError) { setError(requestError.response?.data?.message || requestError.message || "Donation payment could not be prepared."); } finally { setLoading(false); } };
  if (intent) return <UpiPaymentStep intent={intent} title="Donation Payment" description={`Complete the contribution for ${form.name}.`} details={[["Purpose", "Donation"], ["Donor", form.name], ["Donation Amount", `₹${Number(intent.amount).toLocaleString("en-IN")}`]]} onBack={() => setIntent(null)} onSubmit={(data) => submitDonationUpiProof(intent, data)} />;
  const available = config?.upi?.donationEnabled || config?.donation?.gatewayEnabled;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12"><div className="grid overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl lg:grid-cols-[0.85fr_1.15fr]">
    <section className="bg-[#0B2948] p-7 text-white sm:p-10"><HeartHandshake className="text-[#E6CB83]" size={42} /><h1 className="mt-6 text-3xl font-bold">Support meaningful change</h1><p className="mt-4 leading-7 text-slate-300">Choose your donation amount. The QR is generated securely for that exact amount using the organisation’s active payment settings.</p><div className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#E6CB83]">Current method</p><p className="mt-2 text-lg font-bold">{config?.upi?.donationEnabled ? "UPI payment" : "Online payment unavailable"}</p><p className="mt-2 text-sm text-slate-300">{config?.upi?.donationEnabled ? `Payee: ${config.upi.payeeName}` : "Please contact the organisation for assistance."}</p></div><p className="mt-6 flex gap-2 text-sm text-slate-300"><ShieldCheck className="shrink-0 text-[#E6CB83]" size={19} />No receipt is issued until an authorised Admin verifies the payment proof.</p></section>
    <section className="p-6 sm:p-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#287080]">Donation form</p><h2 className="mt-2 text-2xl font-bold text-[#102A43]">Enter contribution details</h2>{error && <p role="alert" className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}{config && !available && <p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">Online payment is currently unavailable. Please contact the organisation.</p>}
      {config?.upi?.donationEnabled && config?.donation?.gatewayEnabled && <div className="mt-5 grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button type="button" onClick={() => setMode("upi")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === "upi" ? "bg-white text-[#0B2948] shadow" : "text-slate-500"}`}><QrCode className="mr-2 inline" size={17} />UPI</button><button type="button" onClick={() => setMode("gateway")} className={`rounded-lg px-3 py-2 text-sm font-semibold ${mode === "gateway" ? "bg-white text-[#0B2948] shadow" : "text-slate-500"}`}><CreditCard className="mr-2 inline" size={17} />Gateway</button></div>}
      <form onSubmit={proceed} className="mt-6 space-y-4">{[["name", "Full Name", "text"], ["email", "Email Address", "email"], ["phone", "Mobile Number", "tel"], ["amount", "Donation Amount (INR)", "number"]].map(([name, label, type]) => <label key={name} className="block text-sm font-semibold text-slate-700">{label}<input name={name} type={type} required={name !== "phone"} min={name === "amount" ? config?.donation?.minimumAmount : undefined} step={name === "amount" ? "0.01" : undefined} className="form-input mt-1" value={form[name]} onChange={update} /></label>)}<div className="rounded-xl bg-slate-50 p-4 text-sm"><div className="flex justify-between"><span>Donation amount</span><strong>₹{Number(form.amount || 0).toLocaleString("en-IN")}</strong></div><div className="mt-2 flex justify-between border-t pt-2 text-base"><span>Total payable</span><strong>₹{Number(form.amount || 0).toLocaleString("en-IN")}</strong></div><p className="mt-2 text-xs text-slate-500">No surcharge, convenience fee or percentage addition.</p></div><button disabled={loading || !available || (mode === "upi" && !config?.upi?.donationEnabled) || (mode === "gateway" && !config?.donation?.gatewayEnabled)} className="primary-button min-h-12 w-full justify-center">{loading ? <><LoaderCircle className="mr-2 animate-spin" size={18} />Preparing payment...</> : "Proceed to Pay"}</button></form>
    </section></div></main>;
};
export default Donate;
